config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
    resources :reviews do
      resources :comments
      resource :bookmark
    end

    resources :reviews do
      resources :comments
      resources :bookmark
    end

    resources :users

    resource :session

    resource :account

    get "about", to: "pages#about"
    get "terms", to: "pages#terms"

    root "pages#home"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :review, uniqueness: { scope: :user }
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :body, presence: true

  profanity_filter :body, :method => 'hollow'

end

app/models/page.rb
class Page < ApplicationRecord

  validates :url, uniqueness: true

  mount_uploader :image, ContentImageUploader

end

app/models/review.rb
class Review < ApplicationRecord

  # add an association that has a one to many relationship
  has_many :comments
  has_many :bookmarks

  # add an association to the user
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  # add the photo uploader
  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :body, length:{ minimum: 10 }
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :restaurant, presence: true
  validates :address, presence: true

  def to_param
    id.to_s + "-" + title.parameterize
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :comments
  has_many :bookmarks

  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def to_param
    username
  end

  mount_uploader :avatar, AvatarUploader

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :check_login

  def show
    redirect_to edit_account_path
  end

  def edit
  end

  def update
    if @current_user.update(form_params)
      flash[:success] = "Your profile has been updated!"
    end

    render "edit"
  end

  def form_params
    params.require(:user).permit(:username, :email, :avatar)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @review = Review.find(params[:review_id])

    @comment = @review.comments.new(params.require(:comment).permit(:body))

    @comment.user = @current_user

    @comment.save

    # go back to the review show page
    redirect_to review_path(@review)

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @content = Page.find_by(url: "home")

    @highly_rated_reviews = Review.where("score >= 8")

    @featured_reviews = Review.where(is_featured: true)

  end

  def about
    @content = Page.find_by(url: "about")
  end

  def terms
    @content = Page.find_by(url: "terms")
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    # check if logged in
    before_action :check_login, except: [:index, :show]


    def index
      # this is our list page for our reviews
      @price = params[:price]
      @cuisine = params[:cuisine]
      @location = params[:location]

      # start with all reviews
      @reviews = Review.all

      # filtering by price
      if @price.present?
        @reviews = @reviews.where(price: @price)
      end

      # filter by cuisine
      if @cuisine.present?
        @reviews = @reviews.where(cuisine: @cuisine)
      end

      # search near the location
      if @location.present?
        @reviews = @reviews.near(@location)
      end

    end

    def new
      # the form for adding a new review
      @review = Review.new
    end

    def create
      # take info from form and add to model
      @review = Review.new(form_params)

      # associate it with the user
      @review.user = @current_user

      # we want to check if the model can be saved
      # if it is, we'll go to home page
      # if it isn't, show the new form

      if @review.save
        redirect_to root_path
      else
        #show the view for new.html.erb
        render "new"

      end

    end

    def show
      # individual review page
      @review = Review.find(params[:id])
    end

    def destroy
      # find the invidiual review
      @review = Review.find(params[:id])

      if @review.user == @current_user
        #destory it
        @review.destroy
      end
        #redirect to homepage
        redirect_to root_path
    end

    def edit
      #find the invidual review to edit
      @review = Review.find(params[:id])

      if @review.user != @current_user
        redirect_to root_path
      elsif @review.created_at < 1.hour.ago
        redirect_to review_path(@review)
      end
    end


    def update
      # find the individual review
      @review = Review.find(params[:id])

      if @review.user != @current_user
        redirect_to root_path
      else
          # update with new info from form
        if @review.update(form_params)
          #redirect to new review page
          redirect_to review_path(@review)
        else
          render "edit"
        end
      end
    end

    def form_params
      params.require(:review).permit(:title, :restaurant, :body, :score, :ambiance, :price, :cuisine, :address, :photo)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # login form
  end

  def create
    # actually try and login
    @form_data = params.require(:session)

    # pull out the username and password from the form data
    @username = @form_data[:username]
    @password = @form_data[:password]

    # check user is who they say they are
    @user = User.find_by(username: @username).try(:authenticate, @password)

    # if there is a user present
    if @user
      # save this user to that user's session
      session[:user_id] = @user.id

      redirect_to root_path
    else
      render "new"
    end

  end

  def destroy
    # log out
    # remove the sessions completely
    reset_session

    #redirect to login page
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show

    @user = User.find_by(username: params[:id])

  end

  def new
    # a form for adding a new user
    @user = User.new
  end

  def create

    # take params from form

    # create a new user
    @user = User.new(form_params)

    # if its valid and it saves, go to the list users page
    # if not, see the form with errors
    if @user.save
      # save the session with the user
      session[:user_id] = @user.id

      flash[:success] = "Welcome to Bien!"

      redirect_to root_path
    else
      render "new"
    end

  end


  # create params as seperate
  def form_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> – Bien Reviews – the best restaurants in the world</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <nav>
        <h1>
          <%= link_to root_path do %>
              <% image_tag "bien-logo.svg" %>
          <% end %>
        </h1>
      </nav>
      <nav>
        <!--- change nav links depending on if logged in or not -->
        <% if is_logged_in? %>
          Hi <%= @current_user.username %>!

          <% if @current_user.is_admin? %>
            <%= link_to "Admin Panel", admin_dashboard_path %>
          <% end %>

          <%= link_to "Add a Review", new_review_path %>
          <%= link_to "Edit Profile", edit_account_path %>
          <%= link_to "Log Out", session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign Up", new_user_path %>
          <%= link_to "Login", new_session_path %>
        <% end %>


      </nav>
    </header>

    <% if flash[:success].present? %>
      <div class="success">
        <p><%= flash[:success] %></p>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <footer>
      Copyright 2017 Bien Reviews – <%= link_to "About", about_path %>
      <%= link_to "Terms", terms_path %>
    </footer>
  </body>
</html>

app/views/pages/_review.html.erb
<div class="review">
  <%= link_to review_path(review) do %>
    <h2><%= review.title %></h2>
    <p>
      <%= review.cuisine %> –
      <%= pluralize review.comments.count, "comment" %>
    </p>
  <% end %>
</div>

app/views/pages/about.html.erb
<%= image_tag @content.image %>

<h1><%= @content.title %></h1>
<%= simple_format @content.body %>

app/views/pages/home.html.erb
<%= image_tag @content.image %>

<h1><%= @content.title %></h1>
<%= simple_format @content.body %>

<h2>Highly Rated Reviews</h2>

<%= render partial: "review", collection: @highly_rated_reviews %>

<h2>Featured Reviews</h2>

<%= render partial: "review", collection: @featured_reviews %>

app/views/pages/terms.html.erb
<h1><%= @content.title %></h1>
<%= simple_format @content.body %>